name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.name.Name
version: ${version}
api-version: 1.13

annoying:
  bStatsId: 12345
  updatePlatforms:
    - platform: MODRINTH
      identifier: name
    - platform: HANGAR
      identifier: ${name}
      author: srnyx
    - platform: SPIGOT
      identifier: 12345
